language: node_js
node_js:
  - 'lts/*'
services:
  - postgresql
  before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - psql -c "create user we with password '123';" -U postgres
  